### ISSUE TITLE
TypeError: layer_norm(): argument 'input' (position 1) must be Tensor, not tuple

### ISSUE THREAD

**Issue by alexv0iceh** [bghira/SimpleTuner#503] opened 2024-06-19 17:20 UTC
Hi there!
I try to train SD3 on linux, but i encounter this error:

Epoch 1/15000, Steps:   0%|                                                                        | 0/30000 [00:02<?, ?it/s]layer_norm(): argument 'input' (position 1) must be Tensor, not tuple
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 2196, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 1676, in main
    model_pred = transformer(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 822, in forward
    return model_forward(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 810, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_sd3.py", line 309, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 494, in checkpoint
    ret = function(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_sd3.py", line 304, in custom_forward
    return module(*inputs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 162, in forward
    norm_hidden_states, gate_msa, shift_mlp, scale_mlp, gate_mlp = self.norm1(hidden_states, emb=temb)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/diffusers/models/normalization.py", line 83, in forward
    x = self.norm(x) * (1 + scale_msa[:, None]) + shift_msa[:, None]
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 201, in forward
    return F.layer_norm(
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2573, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
TypeError: layer_norm(): argument 'input' (position 1) must be Tensor, not tuple

I already tried git-pulling the repo, commenting the line in env about gradient, deleting cache, but it persists.

my mulidataloader looks like this:

[
  {
    "id": "mb_sd3test",
    "type": "local",
    "crop": true,
    "crop_aspect": "square",
    "crop_style": "center",
    "resolution": 1.0,
    "minimum_image_size": 0.25,
    "maximum_image_size": 1.0,
    "target_downsample_size": 1.0,
    "resolution_type": "area",
    "cache_dir_vae": "cache/vae/sd3/mb_sd3_test",
    "instance_data_dir": "/workspace/datasets/mb_sd3test/datasets/mb_sd3_test",
    "disabled": false,
    "skip_file_discovery": "",
    "caption_strategy": "textfile",
    "metadata_backend": "json"
  },
  {
    "id": "text-embeds",
    "type": "local",
    "dataset_type": "text_embeds",
    "default": true,
    "cache_dir": "cache/text/sd3/mb_sd3_test",
    "disabled": false,
    "write_batch_size": 128
  }
]

**Comment by bghira** [comment] 2024-06-19 17:25
duplicate of #461 

i think the gradient checkpointing fix is merged into diffusers now. but if not, you'll have to either manually patch it or disable that option. ensure you also aren't using xformers.

**Comment by alexv0iceh** [comment] 2024-06-19 17:29
yeah, my diffusers are up to date, about xformers: 
(.venv) (base) root@5b3a50bc2fa4:/workspace/SimpleTuner# bash train_sdxl.sh
TRAINER_EXTRA_ARGS not set, defaulting to empty.
Disabling Xformers for Stable Diffusion 3 (https://github.com/huggingface/diffusers/issues/8535)

how do i definitively disable gradient?

**Comment by bghira** [comment] 2024-06-19 17:43
it's in the env file as GRADIENT_CHECKPOINTING

**Comment by alexv0iceh** [comment] 2024-06-19 17:47
thanks!
i found it, it started OOM'ing me (i have a100 40gb) i decreased train_batch_size to 4 and now it gives this:


2024-06-19 18:45:40,490 [ERROR] (VAECache) Error processing image in pool: division by zero, traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/helpers/caching/vae.py", line 690, in _process_images_in_batch
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/SimpleTuner/helpers/caching/vae.py", line 40, in prepare_sample
    prepared_sample = training_sample.prepare()
  File "/workspace/SimpleTuner/helpers/image_manipulation/training_sample.py", line 300, in prepare
    prepared_sample = PreparedSample(
  File "/workspace/SimpleTuner/helpers/image_manipulation/training_sample.py", line 722, in __init__
    image.size[0] / image.size[1]
ZeroDivisionError: division by zero

2024-06-19 18:45:40,490 [ERROR] (VAECache) Error processing image in pool: division by zero, traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/helpers/caching/vae.py", line 690, in _process_images_in_batch
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/SimpleTuner/helpers/caching/vae.py", line 40, in prepare_sample
    prepared_sample = training_sample.prepare()
  File "/workspace/SimpleTuner/helpers/image_manipulation/training_sample.py", line 300, in prepare
    prepared_sample = PreparedSample(
  File "/workspace/SimpleTuner/helpers/image_manipulation/training_sample.py", line 722, in __init__
    image.size[0] / image.size[1]
ZeroDivisionError: division by zero

2024-06-19 18:45:40,491 [ERROR] (VAECache) Error processing image in pool: division by zero, traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/helpers/caching/vae.py", line 690, in _process_images_in_batch
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/SimpleTuner/helpers/caching/vae.py", line 40, in prepare_sample
    prepared_sample = training_sample.prepare()
  File "/workspace/SimpleTuner/helpers/image_manipulation/training_sample.py", line 300, in prepare
    prepared_sample = PreparedSample(
  File "/workspace/SimpleTuner/helpers/image_manipulation/training_sample.py", line 722, in __init__
    image.size[0] / image.size[1]
ZeroDivisionError: division by zero

2024-06-19 18:45:40,491 [ERROR] (VAECache) Error processing image in pool: division by zero, traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/helpers/caching/vae.py", line 690, in _process_images_in_batch
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/SimpleTuner/helpers/caching/vae.py", line 40, in prepare_sample
    prepared_sample = training_sample.prepare()
  File "/workspace/SimpleTuner/helpers/image_manipulation/training_sample.py", line 300, in prepare
    prepared_sample = PreparedSample(
  File "/workspace/SimpleTuner/helpers/image_manipulation/training_sample.py", line 722, in __init__
    image.size[0] / image.size[1]
ZeroDivisionError: division by zero

'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 2196, in <module>
    main()
  File "/workspace/SimpleTuner/train_sdxl.py", line 1461, in main
    for step, batch in random_dataloader_iterator(train_backends):
  File "/workspace/SimpleTuner/helpers/data_backend/factory.py", line 922, in random_dataloader_iterator
    yield (step, next(chosen_iter))
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/workspace/SimpleTuner/.venv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/workspace/SimpleTuner/helpers/data_backend/factory.py", line 635, in <lambda>
    collate_fn=lambda examples: collate_fn(examples),
  File "/workspace/SimpleTuner/helpers/training/collate.py", line 375, in collate_fn
    latent_batch = check_latent_shapes(
  File "/workspace/SimpleTuner/helpers/training/collate.py", line 299, in check_latent_shapes
    test_shape = latents[0].shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by bghira** [comment] 2024-06-19 17:57
```
File "/workspace/SimpleTuner/helpers/image_manipulation/training_sample.py", line 722, in init
image.size[0] / image.size[1]
ZeroDivisionError: division by zero
```

whatever that sample is appears to have some trouble. you'll need to enable debug logging and attach debug.log

**Comment by bghira** [comment] 2024-06-19 17:59
if you have `skip_file_discovery` set to include `vae` it will also cause that kind of error, possibly? i'm not sure, i've never seen these divide by zero errors with PIL.

**Comment by alexv0iceh** [comment] 2024-06-19 18:46
where do i find this setting? not in env or dataloader it seems

**Comment by bghira** [comment] 2024-06-19 18:58
if it's not there, it's not set. you'll have to find out why that image causes a divide-by-zero.

**Comment by alexv0iceh** [comment] 2024-06-19 19:43
i thought maybe issue was with inconsistent image sizes (like 987х987), so i uploaded a dataset full of idela 1024x1024 squares
in it all of the images give same error on Generating aspect bucket cache step after which it gave me this:

2024-06-19 20:39:54,062 [ERROR] (__main__) No images were discovered by the bucket manager in the dataset: cm_sd3., traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 698, in main
    configure_multi_databackend(
  File "/workspace/SimpleTuner/helpers/data_backend/factory.py", line 570, in configure_multi_databackend
    raise Exception(
Exception: No images were discovered by the bucket manager in the dataset: cm_sd3.


do you have thoughts about it?

**Comment by alexv0iceh** [comment] 2024-06-19 19:52
i have a bad feeling about image sizes and crops in general, think the problem is with them, but i'm not sure how

**Comment by bghira** [comment] 2024-06-19 19:53
i would stop setting maximum image size and target downsample size, since you don't have extra-massive images.

**Comment by alexv0iceh** [comment] 2024-06-19 19:54
leave them empty, then?

**Comment by bghira** [comment] 2024-06-20 00:27
null or remove them, yes. make sure to provide --override_dataset_config. make sure to pay close attention to the logs on the console that talk about the bucketing/images. it mentions why they're skipped and so on. you need to share that information and/or be willing to look into it yourself. it's a lot of work to maintain a project like this, doing my training work, and also have short back-and-forths on here.

**Comment by alexv0iceh** [comment] 2024-06-20 18:28
so yeah, here's and update and maybe a suggestion to write down one point in the manual more clearly:

The reason of this error was that i specified path to an exact folder in which images are, while it seems is HAS TO be one folder above it. In the example with HF dataset in sd3 quickstart guide, there are subfolders (including one with images) inside downloaded dataset, so this isn't a problem, but i guess it would helpful to add a note about the need to preserve structure when working with local datasets.

**Comment by bghira** [comment] 2024-06-20 18:29
that's not true, though. 99% of my usage has no subdirectories under the top level directory.

**Comment by alexv0iceh** [comment] 2024-06-20 18:32
just reporting what seemed to fix it for me
neither of crop parameters alterations worked, but when i changed "instance_data_dir" from  "/workspace/datasets/cm_sd3/datasets/cm_sd3test" to "/workspace/datasets/cm_sd3/datasets/" it started seeing images normally

Before:
```
(Rank: 0)  | Bucket     | Image Count 
------------------------------
2024-06-20 18:59:56,324 [ERROR] (__main__) No images were discovered by the bucket manager in the dataset: cm_sd3., traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 698, in main
    configure_multi_databackend(
  File "/workspace/SimpleTuner/helpers/data_backend/factory.py", line 570, in configure_multi_databackend
    raise Exception(
Exception: No images were discovered by the bucket manager in the dataset: cm_sd3.
```
After:

```
(Rank: 0)  | Bucket     | Image Count 
------------------------------
(Rank: 0)  | 1.0        | 32          
2024-06-20 19:07:52,966 [INFO] (DataBackendFactory) (id=cm_sd3) Collecting captions.
Loading captions: 100%|███████████████████████████████████████████████████████████████████| 41/41 [00:00<00:00, 40491.28it/s]
2024-06-20 19:07:52,968 [INFO] (DataBackendFactory) (id=cm_sd3) Initialise text embed pre-computation using the textfile caption strategy. We have 41 captions to process.
2024-06-20 19:07:52,971 [INFO] (DataBackendFactory) (id=cm_sd3) Completed processing 41 captions.
2024-06-20 19:07:52,971 [INFO] (DataBackendFactory) (id=cm_sd3) Creating VAE latent cache.
2024-06-20 19:07:52,972 [INFO] (DataBackendFactory) Configuring data backend: regularisation-data
2024-06-20 19:07:52,972 [ERROR] (__main__) 'Namespace' object has no attribute 'crop', traceback: Traceback (most recent call last):
  File "/workspace/SimpleTuner/train_sdxl.py", line 698, in main
    configure_multi_databackend(
  File "/workspace/SimpleTuner/helpers/data_backend/factory.py", line 407, in configure_multi_databackend
    init_backend = init_backend_config(backend, args, accelerator)
  File "/workspace/SimpleTuner/helpers/data_backend/factory.py", line 62, in init_backend_config
    output["config"]["crop"] = args.crop
AttributeError: 'Namespace' object has no attribute 'crop'
```

**Comment by bghira** [comment] 2024-06-20 20:44
fixed

**Closed** 2024-06-21 20:10 UTC
