### ISSUE TITLE
KeyError: 'time_text_embed.timestep_embedder.linear_1.weight._data'

### ISSUE THREAD

**Issue by ssizd** [bghira/SimpleTuner#751] opened 2024-08-13 07:23 UTC
Hello, I am training on Runpod, and although I successfully conducted training before this error appeared, the actual results were not satisfactory, so I tweaked the configuration file. However, the error started appearing after that. Even after rolling back to the original settings, the error persists. Since the training did run previously, I don't think the issue is with the PyTorch version. My multidatabackend settings are identical to the example, except for the paths. I am attaching the config file as well.

[config.txt](https://github.com/user-attachments/files/16595863/config.txt)

**Comment by bghira** [comment] 2024-08-13 11:55
duplicate of #659

**Closed** 2024-08-13 11:55 UTC
