### ISSUE TITLE
Exception: Error encoding images ['image.jpg']: Calculated padded input size per channel: (2 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by janekm** [bghira/SimpleTuner#461] opened 2024-06-15 19:12 UTC
```
Exception: Error encoding images ['image.jpg']: Calculated padded input size per channel: (2 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size, traceback: Traceback (most recent call last):
  File "/Users/janekmann/sd3/SimpleTuner/helpers/caching/vae.py", line 824, in _encode_images_in_batch
    latents = self.encode_images(
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/helpers/caching/vae.py", line 566, in encode_images
    latents_uncached = self.vae.encode(
                       ^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 264, in encode
    h = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/models/autoencoders/vae.py", line 172, in forward
    sample = down_block(sample)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1478, in forward
    hidden_states = downsampler(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/models/downsampling.py", line 147, in forward
    hidden_states = self.conv(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/janekmann/sd3/SimpleTuner/.venv/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Calculated padded input size per channel: (2 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size
```

I keep getting this error... I can't make sense of it as the images are larger than 1024x1024. Any ideas?

**Comment by bghira** [comment] 2024-06-15 19:18
traditionally there's three things to look for when this error occurs:

- is your xformers build working? this isn't relevant to SD3. make sure xformers is disabled.
- are you using gradient checkpointing? ensure you have the patch from upstream diffusers github which wasn't merged yet as of this morning.
- are you using torch compile / inductor? try disabling this and see whether things change.
- are you using `resolution: 1.0` with `resolution_type='pixel'` ?

essentially, i need to see your `multidatabackend.json` and `sdxl-env.sh`

additionally, stable diffusion 3 has some size constraints to its inputs. i would try training on square-cropped 1024px images.

**Comment by pzzmyc** [comment] 2024-06-15 21:06
> traditionally there's three things to look for when this error occurs:
> 
> * is your xformers build working? this isn't relevant to SD3. make sure xformers is disabled.
> * are you using gradient checkpointing? ensure you have the patch from upstream diffusers github which wasn't merged yet as of this morning.
> * are you using torch compile / inductor? try disabling this and see whether things change.
> * are you using `resolution: 1.0` with `resolution_type='pixel'` ?
> 
> essentially, i need to see your `multidatabackend.json` and `sdxl-env.sh`
> 
> additionally, stable diffusion 3 has some size constraints to its inputs. i would try training on square-cropped 1024px images.

same problem,
![image](https://github.com/bghira/SimpleTuner/assets/43562427/035696fb-eb40-4c3f-a5ee-cb2a43de90af)
![image](https://github.com/bghira/SimpleTuner/assets/43562427/db6bfa3b-67c2-483d-9a77-9b026d1c7677)
![image](https://github.com/bghira/SimpleTuner/assets/43562427/439e60f3-fad4-4683-b982-add4ac378475)

**Comment by janekm** [comment] 2024-06-15 21:08
Thanks a lot for the hints! 
Turns out it was the gradient checkpointing issue, applying the patch from diffusers issues fixed it (this one, for the next person looking at this: https://github.com/huggingface/diffusers/pull/8542 )

**Comment by bghira** [comment] 2024-06-15 21:13
that's a first, though i've only seen this error for checkpointing on Apple system, where the error actually manifests with different text. I really hope they merge that soon.

**Comment by bghira** [comment] 2024-06-15 21:38
duplicated by #463 which shows the other message this manifests through.

**Comment by pzzmyc** [comment] 2024-06-16 16:56
I've identified the cause of this bug. It occurs because the text embeddings and configuration files are cached using default parameters before the correct resolution is set. Even after the resolution is corrected, the system continues to load the cache that was initially created with a resolution of 1. I believe that implementing a mechanism to recache these elements should fix the bug. 
  ![image](https://github.com/bghira/SimpleTuner/assets/43562427/50348d2a-5974-4bdd-a4c5-1ae53389be5a)
--translated from chinese to english by llama

**Comment by bghira** [comment] 2024-06-16 16:58
sorry but that is incorrect. there is indeed a persistent cache but it doesnt cause this error. the resolution doesnt impact text embed generation.

**Comment by pzzmyc** [comment] 2024-06-16 17:02
Thank you for your response. It might have been caused by something else, but indeed, after I deleted all the caches, the error was resolved.

**Comment by bghira** [comment] 2024-06-16 17:05
sometimes that is simpletuner's equivalent of "have you tried turning it off and on again"

**Closed** 2024-06-19 01:34 UTC
Labels: wontfix, upstream-bug
