### ISSUE TITLE
Training SD3 Lora without training at least Lora on top of the Two CLIP is a big issue !

### ISSUE THREAD

**Issue by axel578** [bghira/SimpleTuner#474] opened 2024-06-17 12:29 UTC
Many loras are about training on new concepts, some that aren't 100% aligned with the visual representation CLIP might give for certain words, not being able to train the two clip with lora for SD3 is a big takeaway for me, its near impossible to do correct style and concept training for SD3 without this.

(Carefull some people may be able to achieve training on people face or concept with a bit of success, but its actually becaause the training data of the model has resembling images, and it doesnt deviate a lot).

Its really, really, really important to be able to train the Lora on top of the clip models.

**Comment by bghira** [comment] 2024-06-21 20:28
duplicate of #502

**Closed as completed by bghira** 2024-06-21 20:28 UTC
Labels: enhancement, question, difficult-feature
