### ISSUE TITLE
Incorrect image resizing

### ISSUE THREAD

**Issue by komninoschatzipapas** [bghira/SimpleTuner#354] opened 2024-04-18 15:45 UTC
I'm trying to train using images of size 832x1216 and I'm seeing them being resized on the logs:
```
2024-04-18 14:48:42,262 [DEBUG] (MultiaspectImage) Processing image filename: <PIL.Image.Image image mode=RGB size=832x1216 at 0x7F22ABB71450>
2024-04-18 14:48:42,263 [DEBUG] (MultiaspectImage) Image size before EXIF transform: (832, 1216)
2024-04-18 14:48:42,265 [DEBUG] (MultiaspectImage) Image size after EXIF transform: (832, 1216)
2024-04-18 14:48:42,265 [DEBUG] (MultiaspectImage) Dataset: orion, maximum_image_size: None, target_downsample_size: None
2024-04-18 14:48:42,265 [DEBUG] (MultiaspectImage) Received image for processing: <PIL.Image.Image image mode=RGB size=832x1216 at 0x7F22ABB73BE0>
2024-04-18 14:48:42,265 [DEBUG] (MultiaspectImage) Converted image to RGB for processing: <PIL.Image.Image image mode=RGB size=832x1216 at 0x7F22ABB71420>
2024-04-18 14:48:42,265 [DEBUG] (MultiaspectImage) Resizing image of size (832, 1216) to its new size: 832x1224.
2024-04-18 14:48:42,279 [DEBUG] (MultiaspectImage) Final image size: (832, 1224).
```

Which is unintended as I want to train on 832x1216 and not on the resized 832x1224 resolution.

I looked at the code and it seems like the target size is being calculated on the [prepare_image](https://github.com/bghira/SimpleTuner/blob/21f8e433490c7152eb9da36b57b540a691acfb5e/helpers/multiaspect/image.py#L84) function. That function calls a [calculate_new_size_by_pixel_edge](https://github.com/bghira/SimpleTuner/blob/21f8e433490c7152eb9da36b57b540a691acfb5e/helpers/multiaspect/image.py#L396-L397) function which firstly calculates the image's aspect ratio using [calculate_image_aspect_ratio](https://github.com/bghira/SimpleTuner/blob/21f8e433490c7152eb9da36b57b540a691acfb5e/helpers/multiaspect/image.py#L441) and then multiplies that aspect ratio with the image's smallest side.

However, that logic fails when you have input images whose aspect ratio is a non-terminating decimal. For example, the aspect ratio of 832x1216 is `0,68421053...`. The code will truncate the aspect ratio and then multiply the smallest edge by the truncated aspect ratio resulting in a different target image size than expected.

832x1216 is a common resolution to train on and outlined in the SDXL technical report as shown here:
![sdxl-resolution-cheat-sheet-v0-69sfn578hseb1](https://github.com/bghira/SimpleTuner/assets/29049104/b1ebfab6-2a7a-450f-b1e8-855d95e615b9)

**Comment by bghira** [comment] 2024-04-19 12:12
yeah.. i don't want to touch that. look at the git history for those files. it's fine if you don't hit the exact resolutions you're looking for, and better-off to use `crop: true` and `crop_aspect: preserve` so that it crops down without altering the aspect of the content.

**Comment by komninoschatzipapas** [comment] 2024-04-19 12:26
The issue is that I don't want the images to be cropped nor do I want to train on a different resolution since inference will be done at 832x1216.

It's also not obvious that this is intended. I only realized this trying to debug the other issue I was facing.

It's easy enough to edit this logic on my machine but I imagine other users will face this. I'm not sure what the advantage of resizing like this is.

**Comment by bghira** [comment] 2024-04-19 12:51
i mean, the problem is this is a general trainer which is meant as a starting point for normal end-users to just train a model with.

in my case i've used millions of images, and a few pixels off here and there doesn't matter.

what's more important for the project is correctness. like i said, if you look at the git history of the files, you'll see how big of a pain this is.

go ahead and change the logic however you see fit - run it locally, run into the same problems.

if you only ever use a single resolution, you can probably get away with it.  but EVERYTHING has to have the same resolution in a single batch, and using too much significant figures in the aspect ratio is going to cause major problems.

the image sizes have to align to 64 pixels. your proposed size does align to 64, but unfortunately, once the aspect ratio is rounded off, it changes slightly.

this is absolutely preferable to not rounding, where you'd end up with more than 1000 buckets where each one has just 2 to 5 images in each, which isn't even typically enough to satisfy a single batch.

**Comment by komninoschatzipapas** [comment] 2024-04-19 15:08
I see. There do exist use cases where high precision is needed though. I think in any case there should be some type of warning if the images are being resized cause that can introduce artifacts. Or an option to turn the resizing off for us that are training on one res. Just a suggestion.

**Comment by bghira** [comment] 2024-04-19 16:11
there is a variable that is used in some places, `aspect_ratio_rounding` but it's not passed around thoroughly enough to make it a configurable option in the dataset without doing work on that. but it would allow you to modify the precision of the aspect buckets so that you can just make it much longer.

it would need to be added to the init_backend_config method inside factory.py so that this config value becomes strongly associated with the dataset. it can then be accessed anywhere via the StateTracker class, if you have the dataset backend id. that's not always immediately available, which is why i did not add this as a config option.

however, the information is here if you wish to attempt doing so. the problem i foresee is a complication with unit tests that might make other expectations. but once you run those, you might understand why this is done the way it is. or i will be corrected and the code will be fixed.

a word of caution is to avoid adjusting anything that would result in the defaults behaving differently. there are quite-large datasets that are in use, and any updates that cause them to recalculate things for millions of images would be unfortunate. in the best case it will just take a while, but in the worst case you end up with annoying tensor size mismatch errors.

**Comment by bghira** [comment] 2024-04-19 16:34
you know, it would probably be easiest to add it to arguments.py as a global option. though it's definitely not the approach i prefer, it would get the job done for you.

you can access these via `StateTracker.get_args().parameter_name` - i'm not sure if i'd accept this as a PR as i'm not sure i'd ever personally have a use for it. but if you're willing to implement it and maintain any issues that arise, i would consider inclusion

**Comment by komninoschatzipapas** [comment] 2024-04-19 17:32
![CleanShot 2024-04-19 at 20 25 57](https://github.com/bghira/SimpleTuner/assets/29049104/1eb697e2-e733-437f-8f48-8e8b2a51ecd4)

What do you think of something like this? Obviously, `args` is not available in that context but I think the concept is clearly illustrated.

Note that on line 88, setting the resolution to `original_width / original_height` won't work with aspect ratios that are non-terminating decimals, so I reused the existing helper function with a higher rounding number.

Again I'm new to this codebase so I'm ignorant to a lot of things but it did seem to work like that on my machine.

**Comment by komninoschatzipapas** [comment] 2024-04-19 18:16
Yes, you're right. I was setting `new_aspect_ratio`.

And yea it does seem like what you're suggesting is a better solution. With a high enough aspect ratio rounding, any resolution should remain intact.

If you're happy to move forward with this, I can get a PR opened.

**Comment by bghira** [comment] 2024-04-19 18:37
go for it. opening the PR will allow me to approve the tests to run, which will make sure no regressions are introduced.

it'll be likely some tests have to be updated

**Comment by bghira** [comment] 2024-04-19 18:59
if you don't mind, i'll just add this now, since i'm already working on things.

**Comment by komninoschatzipapas** [comment] 2024-04-19 19:03
Sure, not a problem. Thank you!

**Comment by bghira** [comment] 2024-04-19 19:10
```
...........F......F..E................sss.....
======================================================================
ERROR: test_prepare_image_valid (test_image.TestMultiaspectImage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bghira/src/SimpleTuner/tests/test_image.py", line 156, in test_prepare_image_valid
    MultiaspectImage.prepare_image(
  File "/Users/bghira/src/SimpleTuner/helpers/multiaspect/image.py", line 87, in prepare_image
    MultiaspectImage.calculate_new_size_by_pixel_edge(
  File "/Users/bghira/src/SimpleTuner/helpers/multiaspect/image.py", line 397, in calculate_new_size_by_pixel_edge
    aspect_ratio = MultiaspectImage.calculate_image_aspect_ratio((W, H))
  File "/Users/bghira/src/SimpleTuner/helpers/multiaspect/image.py", line 458, in calculate_image_aspect_ratio
    aspect_ratio = round(width / height, rounding)
TypeError: 'Mock' object cannot be interpreted as an integer

======================================================================
FAIL: test_aspect_ratio_calculation (test_image.TestMultiaspectImage)
Test that the aspect ratio calculation returns expected results.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bghira/src/SimpleTuner/tests/test_image.py", line 36, in test_aspect_ratio_calculation
    self.assertEqual(
AssertionError: 1.8 != 1.78

======================================================================
FAIL: test_image_resize (test_image.TestMultiaspectImage)
Test that images are resized to the expected dimensions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bghira/src/SimpleTuner/tests/test_image.py", line 65, in test_image_resize
    self.assertEqual(resized_image.size, expected_size)
AssertionError: Tuples differ: (1840, 1024) != (1824, 1024)

First differing element 0:
1840
1824

- (1840, 1024)
?     -

+ (1824, 1024)
?    +


----------------------------------------------------------------------
Ran 46 tests in 23.255s

FAILED (failures=2, errors=1, skipped=3)
```

the glorious nightmare

**Closed** 2024-04-19 19:24 UTC
Labels: enhancement, help wanted, good first issue, question

**Comment by bghira** [comment] 2024-04-23 23:41
i went through the rounding code again after dealing with 64px image sizes in deepfloyd, where i need to adjust the bucket interval to 8px rather than 64px, for seemingly obvious reasons (in hindsight)

when looking at this i discovered we are in fact rounding up quite intentionally in the pixel resize code. it means that 1216x832 becomes 1216x896.

so that's fixed now. default settings should work for you, no need for million precision points.
