### ISSUE TITLE
error when trying to train flux on runpod

### ISSUE THREAD

**Issue by etha302** [bghira/SimpleTuner#736] opened 2024-08-12 04:29 UTC
this is the error i get every time:

cannot access local variable 'model_max_seq_length' where it is not associated with a value
Traceback (most recent call last):
  File "/workspace/SimpleTuner/train.py", line 2753, in <module>
    main()
  File "/workspace/SimpleTuner/train.py", line 277, in main
    args = parse_args()
           ^^^^^^^^^^^^
  File "/workspace/SimpleTuner/helpers/arguments.py", line 1983, in parse_args
    f"Updating T5 XXL tokeniser max length to {model_max_seq_length} for Flux."
                                               ^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'model_max_seq_length' where it is not associated with a value

if anyone knows the solution, please let me know. it is refering to train.py, but i just dont know how to fix it.

**Comment by mhirki** [comment] 2024-08-12 06:43
This looks like a duplicate of issue #726.

**Closed** 2024-08-12 13:09 UTC
